#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : SDL_net
Version  : 1.2.8
Release  : 12
URL      : https://www.libsdl.org/projects/SDL_net/release/SDL_net-1.2.8.tar.gz
Source0  : https://www.libsdl.org/projects/SDL_net/release/SDL_net-1.2.8.tar.gz
Summary  : SDL portable network library
Group    : Development/Tools
License  : Zlib
Requires: SDL_net-lib = %{version}-%{release}
Requires: SDL_net-license = %{version}-%{release}
BuildRequires : SDL-dev
BuildRequires : SDL-dev32
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkg-config

%description
This is a portable network library for use with SDL.

%package dev
Summary: dev components for the SDL_net package.
Group: Development
Requires: SDL_net-lib = %{version}-%{release}
Provides: SDL_net-devel = %{version}-%{release}
Requires: SDL_net = %{version}-%{release}

%description dev
dev components for the SDL_net package.


%package dev32
Summary: dev32 components for the SDL_net package.
Group: Default
Requires: SDL_net-lib32 = %{version}-%{release}
Requires: SDL_net-dev = %{version}-%{release}

%description dev32
dev32 components for the SDL_net package.


%package lib
Summary: lib components for the SDL_net package.
Group: Libraries
Requires: SDL_net-license = %{version}-%{release}

%description lib
lib components for the SDL_net package.


%package lib32
Summary: lib32 components for the SDL_net package.
Group: Default
Requires: SDL_net-license = %{version}-%{release}

%description lib32
lib32 components for the SDL_net package.


%package license
Summary: license components for the SDL_net package.
Group: Default

%description license
license components for the SDL_net package.


%prep
%setup -q -n SDL_net-1.2.8
pushd ..
cp -a SDL_net-1.2.8 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568876896
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check
cd ../build32;
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1568876896
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/SDL_net
cp COPYING %{buildroot}/usr/share/package-licenses/SDL_net/COPYING
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/SDL/SDL_net.h
/usr/lib64/libSDL_net.so
/usr/lib64/pkgconfig/SDL_net.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libSDL_net.so
/usr/lib32/pkgconfig/32SDL_net.pc
/usr/lib32/pkgconfig/SDL_net.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSDL_net-1.2.so.0
/usr/lib64/libSDL_net-1.2.so.0.8.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libSDL_net-1.2.so.0
/usr/lib32/libSDL_net-1.2.so.0.8.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/SDL_net/COPYING
