#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : SDL_net
Version  : 1.2.8
Release  : 13
URL      : https://www.libsdl.org/projects/SDL_net/release/SDL_net-1.2.8.tar.gz
Source0  : https://www.libsdl.org/projects/SDL_net/release/SDL_net-1.2.8.tar.gz
Summary  : SDL portable network library
Group    : Development/Tools
License  : Zlib
Requires: SDL_net-lib = %{version}-%{release}
Requires: SDL_net-license = %{version}-%{release}
BuildRequires : SDL-dev
BuildRequires : pkg-config

%description
This is a portable network library for use with SDL.

%package dev
Summary: dev components for the SDL_net package.
Group: Development
Requires: SDL_net-lib = %{version}-%{release}
Provides: SDL_net-devel = %{version}-%{release}
Requires: SDL_net = %{version}-%{release}

%description dev
dev components for the SDL_net package.


%package lib
Summary: lib components for the SDL_net package.
Group: Libraries
Requires: SDL_net-license = %{version}-%{release}

%description lib
lib components for the SDL_net package.


%package license
Summary: license components for the SDL_net package.
Group: Default

%description license
license components for the SDL_net package.


%prep
%setup -q -n SDL_net-1.2.8
cd %{_builddir}/SDL_net-1.2.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600306912
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1600306912
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/SDL_net
cp %{_builddir}/SDL_net-1.2.8/COPYING %{buildroot}/usr/share/package-licenses/SDL_net/6827ebf4d3992ba02ac87ddc46963fe8af56d6ea
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/SDL/SDL_net.h
/usr/lib64/libSDL_net.so
/usr/lib64/pkgconfig/SDL_net.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSDL_net-1.2.so.0
/usr/lib64/libSDL_net-1.2.so.0.8.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/SDL_net/6827ebf4d3992ba02ac87ddc46963fe8af56d6ea
