#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : SDL_net
Version  : 1.2.8
Release  : 3
URL      : https://www.libsdl.org/projects/SDL_net/release/SDL_net-1.2.8.tar.gz
Source0  : https://www.libsdl.org/projects/SDL_net/release/SDL_net-1.2.8.tar.gz
Summary  : SDL portable network library
Group    : Development/Tools
License  : Zlib
Requires: SDL_net-lib
BuildRequires : SDL-dev

%description
This is a portable network library for use with SDL.

%package dev
Summary: dev components for the SDL_net package.
Group: Development
Requires: SDL_net-lib
Provides: SDL_net-devel

%description dev
dev components for the SDL_net package.


%package lib
Summary: lib components for the SDL_net package.
Group: Libraries

%description lib
lib components for the SDL_net package.


%prep
cd ..
%setup -q -n SDL_net-1.2.8

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/SDL/SDL_net.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
